I94PORT = [
   ('ALC','ALCAN','AK'),
   ('ANC','ANCHORAGE','AK'),
   ('BAR','BAKERAAF-BAKERISLAND','AK'),
   ('DAC','DALTONSCACHE','AK'),
   ('PIZ','DEWSTATIONPTLAYDEW','AK'),
   ('DTH','DUTCHHARBOR','AK'),
   ('EGL','EAGLE','AK'),
   ('FRB','FAIRBANKS','AK'),
   ('HOM','HOMER','AK'),
   ('HYD','HYDER','AK'),
   ('JUN','JUNEAU','AK'),
   ('5KE','KETCHIKAN','AK'),
   ('KET','KETCHIKAN','AK'),
   ('MOS','MOSESPOINTINTERMEDIATE','AK'),
   ('NIK','NIKISKI','AK'),
   ('NOM','NOM','AK'),
   ('PKC','POKERCREEK','AK'),
   ('ORI','PORTLIONSSPB','AK'),
   ('SKA','SKAGWAY','AK'),
   ('SNP','ST.PAULISLAND','AK'),
   ('TKI','TOKEEN','AK'),
   ('WRA','WRANGELL','AK'),
   ('HSV','MADISONCOUNTY-HUNTSVILLE','AL'),
   ('MOB','MOBILE','AL'),
   ('LIA','LITTLEROCK','AR(BPS)'),
   ('ROG','ROGERSARPT','AR'),
   ('DOU','DOUGLAS','AZ'),
   ('LUK','LUKEVILLE','AZ'),
   ('MAP','MARIPOSA','AZ'),
   ('NAC','NACO','AZ'),
   ('NOG','NOGALES','AZ'),
   ('PHO','PHOENIX','AZ'),
   ('POR','PORTAL','AZ'),
   ('SLU','SANLUIS','AZ'),
   ('SAS','SASABE','AZ'),
   ('TUC','TUCSON','AZ'),
   ('YUI','YUMA','AZ'),
   ('AND','ANDRADE','CA'),
   ('BUR','BURBANK','CA'),
   ('CAL','CALEXICO','CA'),
   ('CAO','CAMPO','CA'),
   ('FRE','FRESNO','CA'),
   ('ICP','IMPERIALCOUNTY','CA'),
   ('LNB','LONGBEACH','CA'),
   ('LOS','LOSANGELES','CA'),
   ('BFL','MEADOWSFIELD-BAKERSFIELD','CA'),
   ('OAK','OAKLAND','CA'),
   ('ONT','ONTARIO','CA'),
   ('OTM','OTAYMESA','CA'),
   ('BLT','PACIFIC, HWY. STATION','CA'),
   ('PSP','PALMSPRINGS','CA'),
   ('SAC','SACRAMENTO','CA'),
   ('SLS','SALINAS','CA(BPS)'),
   ('SDP','SANDIEGO','CA'),
   ('SFR','SANFRANCISCO','CA'),
   ('SNJ','SANJOSE','CA'),
   ('SLO','SANLUISOBISPO','CA'),
   ('SLI','SANLUISOBISPO','CA(BPS)'),
   ('SPC','SANPEDRO','CA'),
   ('SYS','SANYSIDRO','CA'),
   ('SAA','SANTAANA','CA'),
   ('STO','STOCKTON','CA(BPS)'),
   ('TEC','TECATE','CA'),
   ('TRV','TRAVIS-AFB','CA'),
   ('APA','ARAPAHOECOUNTY','CO'),
   ('ASE','ASPEN','CO#ARPT'),
   ('COS','COLORADOSPRINGS','CO'),
   ('DEN','DENVER','CO'),
   ('DRO','LAPLATA-DURANGO','CO'),
   ('BDL','BRADLEYINTERNATIONAL','CT'),
   ('BGC','BRIDGEPORT','CT'),
   ('GRT','GROTON','CT'),
   ('HAR','HARTFORD','CT'),
   ('NWH','NEWHAVEN','CT'),
   ('NWL','NEWLONDON','CT'),
   ('TST','NEWINGTONDATACENTERTEST','CT'),
   ('WAS','WASHINGTONDC',''),
   ('DOV','DOVERAFB','DE'),
   ('DVD','DOVER-AFB','DE'),
   ('WLL','WILMINGTON','DE'),
   ('BOC','BOCAGRANDE','FL'),
   ('SRQ','BRADENTON-SARASOTA','FL'),
   ('CAN','CAPECANAVERAL','FL'),
   ('DAB','DAYTONABEACHINTERNATIONAL','FL'),
   ('FRN','FERNANDINA','FL'),
   ('FTL','FORTLAUDERDALE','FL'),
   ('FMY','FORTMYERS','FL'),
   ('FPF','FORTPIERCE','FL'),
   ('HUR','HURLBURTFIELD','FL'),
   ('GNV','JRALISONMUNI-GAINESVILLE','FL'),
   ('JAC','JACKSONVILLE','FL'),
   ('KEY','KEYWEST','FL'),
   ('LEE','LEESBURGMUNICIPALAIRPORT','FL'),
   ('MLB','MELBOURNE','FL'),
   ('MIA','MIAMI','FL'),
   ('APF','NAPLES','FL#ARPT'),
   ('OPF','OPALOCKA','FL'),
   ('ORL','ORLANDO','FL'),
   ('PAN','PANAMACITY','FL'),
   ('PEN','PENSACOLA','FL'),
   ('PCF','PORTCANAVERAL','FL'),
   ('PEV','PORTEVERGLADES','FL'),
   ('PSJ','PORTSTJOE','FL'),
   ('SFB','SANFORD','FL'),
   ('SGJ','STAUGUSTINEARPT','FL'),
   ('SAU','STAUGUSTINE','FL'),
   ('FPR','STLUCIECOUNTY','FL'),
   ('SPE','STPETERSBURG','FL'),
   ('TAM','TAMPA','FL'),
   ('WPB','WESTPALMBEACH','FL'),
   ('ATL','ATLANTA','GA'),
   ('BRU','BRUNSWICK','GA'),
   ('AGS','BUSHFIELD-AUGUSTA','GA'),
   ('SAV','SAVANNAH','GA'),
   ('AGA','AGANA','GU'),
   ('HHW','HONOLULU','HI'),
   ('OGG','KAHULUI-MAUI','HI'),
   ('KOA','KEAHOLE-KONA','HI'),
   ('LIH','LIHUE','HI'),
   ('CID','CEDARRAPIDS/IOWACITY','IA'),
   ('DSM','DESMOINES','IA'),
   ('BOI','AIRTERM.(GOWENFLD)BOISE','ID'),
   ('EPI','EASTPORT','ID'),
   ('IDA','FANNINGFIELD-IDAHOFALLS','ID'),
   ('PTL','PORTHILL','ID'),
   ('SPI','CAPITAL-SPRINGFIELD','IL'),
   ('CHI','CHICAGO','IL'),
   ('DPA','DUPAGECOUNTY','IL'),
   ('PIA','GREATERPEORIA','IL'),
   ('RFD','GREATERROCKFORD','IL'),
   ('UGN','MEMORIAL-WAUKEGAN','IL'),
   ('GAR','GARY','IN'),
   ('HMM','HAMMOND','IN'),
   ('INP','INDIANAPOLIS','IN'),
   ('MRL','MERRILLVILLE','IN'),
   ('SBN','SOUTHBEND','IN'),
   ('ICT','MID-CONTINENT-WITCHITA','KS'),
   ('LEX','BLUEGRASS-LEXINGTON','KY'),
   ('LOU','LOUISVILLE','KY'),
   ('BTN','BATONROUGE','LA'),
   ('LKC','LAKECHARLES','LA'),
   ('LAK','LAKECHARLES','LA(BPS)'),
   ('MLU','MONROE','LA'),
   ('MGC','MORGANCITY','LA'),
   ('NOL','NEWORLEANS','LA'),
   ('BOS','BOSTON','MA'),
   ('GLO','GLOUCESTER','MA'),
   ('BED','HANSCOMFIELD-BEDFORD','MA'),
   ('LYN','LYNDEN','WA'),
   ('ADW','ANDREWSAFB','MD'),
   ('BAL','BALTIMORE','MD'),
   ('MKG','MUSKEGON','MD'),
   ('PAX','PATUXENTRIVER','MD'),
   ('BGM','BANGOR','ME'),
   ('BOO','BOOTHBAYHARBOR','ME'),
   ('BWM','BRIDGEWATER','ME'),
   ('BCK','BUCKPORT','ME'),
   ('CLS','CALAIS','ME'),
   ('CRB','CARIBOU','ME'),
   ('COB','COBURNGORE','ME'),
   ('EST','EASTCOURT','ME'),
   ('EPT','EASTPORTMUNICIPAL','ME'),
   ('EPM','EASTPORT','ME'),
   ('FOR','FORESTCITY','ME'),
   ('FTF','FORTFAIRFIELD','ME'),
   ('FTK','FORTKENT','ME'),
   ('HML','HAMIIN','ME'),
   ('HTM','HOULTON','ME'),
   ('JKM','JACKMAN','ME'),
   ('KAL','KALISPEL','MT'),
   ('LIM','LIMESTONE','ME'),
   ('LUB','LUBEC','ME'),
   ('MAD','MADAWASKA','ME'),
   ('POM','PORTLAND','ME'),
   ('RGM','RANGELEY','ME(BPS)'),
   ('SBR','SOUTHBREWER','ME'),
   ('SRL','STAURELIE','ME'),
   ('SPA','STPAMPILE','ME'),
   ('VNB','VANBUREN','ME'),
   ('VCB','VANCEBORO','ME'),
   ('AGN','ALGONAC','MI'),
   ('ALP','ALPENA','MI'),
   ('BCY','BAYCITY','MI'),
   ('DET','DETROIT','MI'),
   ('GRP','GRANDRAPIDS','MI'),
   ('GRO','GROSSEISLE','MI'),
   ('ISL','ISLEROYALE','MI'),
   ('MRC','MARINECITY','MI'),
   ('MRY','MARYSVILLE','MI'),
   ('PTK','OAKLANDCOUNTY-PONTIAC','MI'),
   ('PHU','PORTHURON','MI'),
   ('RBT','ROBERTSLANDING','MI'),
   ('SAG','SAGINAW','MI'),
   ('SSM','SAULTSTE.MARIE','MI'),
   ('SCL','STCLAIR','MI'),
   ('YIP','WILLOWRUN-YPSILANTI','MI'),
   ('BAU','BAUDETTE','MN'),
   ('CAR','CARIBOUMUNICIPALAIRPORT','MN'),
   ('GTF','CollapsedintoINT','MN'),
   ('INL','CollapsedintoINT','MN'),
   ('CRA','CRANELAKE','MN'),
   ('MIC','CRYSTALMUNICIPALAIRPORT','MN'),
   ('DUL','DULUTH','MN'),
   ('ELY','ELY','MN'),
   ('GPM','GRANDPORTAGE','MN'),
   ('SVC','GRANTCOUNTY-SILVERCITY','MN'),
   ('INT','INT''LFALLS','MN'),
   ('LAN','LANCASTER','MN'),
   ('MSP','MINN./STPAUL','MN'),
   ('LIN','NORTHERNSVCCENTER','MN'),
   ('NOY','NOYES','MN'),
   ('PIN','PINECREEK','MN'),
   ('48Y','PINECREEKBORDERARPT','MN'),
   ('RAN','RAINER','MN'),
   ('RST','ROCHESTER','MN'),
   ('ROS','ROSEAU','MN'),
   ('SPM','STPAUL','MN'),
   ('WSB','WARROAD INTL, SPB','MN'),
   ('WAR','WARROAD','MN'),
   ('KAN','KANSASCITY','MO'),
   ('SGF','SPRINGFIELD-BRANSON','MO'),
   ('STL','STLOUIS','MO'),
   ('WHI','WHITETAIL','MT'),
   ('WHM','WILDHORSE','MT'),
   ('GPT','BILOXIREGIONAL','MS'),
   ('GTR','GOLDENTRIANGLELOWNDESCNTY','MS'),
   ('GUL','GULFPORT','MS'),
   ('PAS','PASCAGOULA','MS'),
   ('JAN','THOMPSONFIELD-JACKSON','MS'),
   ('BIL','BILLINGS','MT'),
   ('BTM','BUTTE','MT'),
   ('CHF','CHIEFMT','MT'),
   ('CTB','CUTBANKMUNICIPAL','MT'),
   ('CUT','CUTBANK','MT'),
   ('DLB','DELBONITA','MT'),
   ('EUR','EUREKA','MT(BPS)'),
   ('BZN','GALLATINFIELD-BOZEMAN','MT'),
   ('FCA','GLACIERNATIONALPARK','MT'),
   ('GGW','GLASGOW','MT'),
   ('GRE','GREATFALLS','MT'),
   ('HVR','HAVRE','MT'),
   ('HEL','HELENA','MT'),
   ('LWT','LEWISTON','MT'),
   ('MGM','MORGAN','MT'),
   ('OPH','OPHEIM','MT'),
   ('PIE','PIEGAN','MT'),
   ('RAY','RAYMOND','MT'),
   ('ROO','ROOSVILLE','MT'),
   ('SCO','SCOBEY','MT'),
   ('SWE','SWEETGTASS','MT'),
   ('TRL','TRIALCREEK','MT'),
   ('TUR','TURNER','MT'),
   ('WCM','WILLOWCREEK','MT'),
   ('CLT','CHARLOTTE','NC'),
   ('FAY','FAYETTEVILLE','NC'),
   ('MRH','MOREHEADCITY','NC'),
   ('FOP','MORRISFIELDSAAF','NC'),
   ('GSO','PIEDMONTTRIADINTLAIRPORT','NC'),
   ('RDU','RALEIGH/DURHAM','NC'),
   ('SSC','SHAWAFB-SUMTER','NC'),
   ('WIL','WILMINGTON','NC'),
   ('AMB','AMBROSE','ND'),
   ('ANT','ANTLER','ND'),
   ('CRY','CARBURY','ND'),
   ('DNS','DUNSEITH','ND'),
   ('FAR','FARGO','ND'),
   ('FRT','FORTUNA','ND'),
   ('GRF','GRANDFORKS','ND'),
   ('HNN','HANNAH','ND'),
   ('HNS','HANSBORO','ND'),
   ('MAI','MAIDA','ND'),
   ('MND','MINOT','ND'),
   ('NEC','NECHE','ND'),
   ('NOO','NOONAN','ND'),
   ('NRG','NORTHGATE','ND'),
   ('PEM','PEMBINA','ND'),
   ('SAR','SARLES','ND'),
   ('SHR','SHERWOOD','ND'),
   ('SJO','STJOHN','ND'),
   ('WAL','WALHALLA','ND'),
   ('WHO','WESTHOPE','ND'),
   ('WND','WILLISTON','ND'),
   ('OMA','OMAHA','NE'),
   ('LEB','LEBANON','NH'),
   ('MHT','MANCHESTER','NH'),
   ('PNH','PITTSBURG','NH'),
   ('PSM','PORTSMOUTH','NH'),
   ('BYO','BAYONNE','NJ'),
   ('CNJ','CAMDEN','NJ'),
   ('HOB','HOBOKEN','NJ'),
   ('JER','JERSEYCITY','NJ'),
   ('WRI','MCGUIREAFB-WRIGHTSOWN','NJ'),
   ('MMU','MORRISTOWN','NJ'),
   ('NEW','NEWARK/TETERBORO','NJ'),
   ('PER','PERTHAMBOY','NJ'),
   ('ACY','POMONAFIELD-ATLANTICCITY','NJ'),
   ('ALA','ALAMAGORDO','NM(BPS)'),
   ('ABQ','ALBUQUERQUE','NM'),
   ('ANP','ANTELOPEWELLS','NM'),
   ('CRL','CARLSBAD','NM'),
   ('COL','COLUMBUS','NM'),
   ('CDD','CRANELAKE-ST.LOUISCNTY','NM'),
   ('DNM','DEMING','NM(BPS)'),
   ('LAS','LASCRUCES','NM'),
   ('LOB','LORDSBURG','NM(BPS)'),
   ('RUI','RUIDOSO','NM'),
   ('STR','SANTATERESA','NM'),
   ('RNO','CANNONINTL-RENO/TAHOE','NV'),
   ('FLX','FALLONMUNICIPALAIRPORT','NV'),
   ('LVG','LASVEGAS','NV'),
   ('REN','RENO','NV'),
   ('ALB','ALBANY','NY'),
   ('AXB','ALEXANDRIABAY','NY'),
   ('BUF','BUFFALO','NY'),
   ('CNH','CANNONCORNERS','NY'),
   ('CAP','CAPEVINCENT','NY'),
   ('CHM','CHAMPLAIN','NY'),
   ('CHT','CHATEAUGAY','NY'),
   ('CLA','CLAYTON','NY'),
   ('FTC','FORTCOVINGTON','NY'),
   ('LAG','LAGUARDIA','NY'),
   ('LEW','LEWISTON','NY'),
   ('MAS','MASSENA','NY'),
   ('MAG','MCGUIREAFB','NY'),
   ('MOO','MOORES','NY'),
   ('MRR','MORRISTOWN','NY'),
   ('NYC','NEWYORK','NY'),
   ('NIA','NIAGARAFALLS','NY'),
   ('OGD','OGDENSBURG','NY'),
   ('OSW','OSWEGO','NY'),
   ('ELM','REGIONALARPT-HORSEHEAD','NY'),
   ('ROC','ROCHESTER','NY'),
   ('ROU','ROUSESPOINT','NY'),
   ('SWF','STEWART-ORANGECNTY','NY'),
   ('SYR','SYRACUSE','NY'),
   ('THO','THOUSANDISLANDBRIDGE','NY'),
   ('TRO','TROUTRIVER','NY'),
   ('WAT','WATERTOWN','NY'),
   ('HPN','WESTCHESTER-WHITEPLAINS','NY'),
   ('WRB','WHIRLPOOLBRIDGE','NY'),
   ('YOU','YOUNGSTOWN','NY'),
   ('AKR','AKRON','OH'),
   ('ATB','ASHTABULA','OH'),
   ('CIN','CINCINNATI','OH'),
   ('CLE','CLEVELAND','OH'),
   ('CLM','COLUMBUS','OH'),
   ('LOR','LORAIN','OH'),
   ('MBO','MARBLEHEADS','OH'),
   ('SDY','SANDUSKY','OH'),
   ('TOL','TOLEDO','OH'),
   ('OKC','OKLAHOMACITY','OK'),
   ('TUL','TULSA','OK'),
   ('AST','ASTORIA','OR'),
   ('COO','COOSBAY','OR'),
   ('HIO','HILLSBORO','OR'),
   ('MED','MEDFORD','OR'),
   ('NPT','NEWPORT','OR'),
   ('POO','PORTLAND','OR'),
   ('PUT','PUT-IN-BAY','OH'),
   ('RDM','ROBERTSFIELDS-REDMOND','OR'),
   ('ERI','ERIE','PA'),
   ('MDT','HARRISBURG','PA'),
   ('HSB','HARRISONBURG','PA'),
   ('PHI','PHILADELPHIA','PA'),
   ('PIT','PITTSBURG','PA'),
   ('AGU','AGUADILLA','PR'),
   ('BQN','BORINQUEN-AGUADILLO','PR'),
   ('JCP','CULEBRA-BENJAMINRIVERA','PR'),
   ('ENS','ENSENADA','PR'),
   ('FAJ','FAJARDO','PR'),
   ('HUM','HUMACAO','PR'),
   ('JOB','JOBOS','PR'),
   ('MAY','MAYAGUEZ','PR'),
   ('PON','PONCE','PR'),
   ('PSE','PONCE-MERCEDITA','PR'),
   ('SAJ','SANJUAN','PR'),
   ('VQS','VIEQUES-ARPT','PR'),
   ('PRO','PROVIDENCE','RI'),
   ('PVD','THEODOREFRANCIS-WARWICK','RI'),
   ('CHL','CHARLESTON','SC'),
   ('CAE','COLUMBIA','SC#ARPT'),
   ('GEO','GEORGETOWN','SC'),
   ('GSP','GREENVILLE','SC'),
   ('GRR','GREER','SC'),
   ('MYR','MYRTLEBEACH','SC'),
   ('SPF','BLACK HILLS, SPEARFISH','SD'),
   ('HON','HOWESREGIONALARPT-HURON','SD'),
   ('SAI','SAIPAN','SPN'),
   ('TYS','MCGHEETYSON-ALCOA','TN'),
   ('MEM','MEMPHIS','TN'),
   ('NSV','NASHVILLE','TN'),
   ('TRI','TRICITYARPT','TN'),
   ('ADS','ADDISONAIRPORT-ADDISON','TX'),
   ('ADT','AMISTADDAM','TX'),
   ('ANZ','ANZALDUAS','TX'),
   ('AUS','AUSTIN','TX'),
   ('BEA','BEAUMONT','TX'),
   ('BBP','BIGBENDPARK','TX(BPS)'),
   ('SCC','BPSPECCOORD.CTR','TX'),
   ('BTC','BPTACTICALUNIT','TX'),
   ('BOA','BRIDGEOFAMERICAS','TX'),
   ('BRO','BROWNSVILLE','TX'),
   ('CRP','CORPUSCHRISTI','TX'),
   ('DAL','DALLAS','TX'),
   ('DLR','DELRIO','TX'),
   ('DNA','DONNA','TX'),
   ('EGP','EAGLEPASS','TX'),
   ('ELP','ELPASO','TX'),
   ('FAB','FABENS','TX'),
   ('FAL','FALCONHEIGHTS','TX'),
   ('FTH','FORTHANCOCK','TX'),
   ('AFW','FORT WORTH ALLIANCE','TX'),
   ('FPT','FREEPORT','TX'),
   ('GAL','GALVESTON','TX'),
   ('HLG','HARLINGEN','TX'),
   ('HID','HIDALGO','TX'),
   ('HOU','HOUSTON','TX'),
   ('SGR','HULL FIELD, SUGAR LAND ARPT','TX'),
   ('LLB','JUAREZ-LINCOLN BRIDGE','TX'),
   ('LCB','LAREDO COLUMBIA BRIDGE','TX'),
   ('LRN','LAREDO NORTH','TX'),
   ('LAR','LAREDO','TX'),
   ('LSE','LOS EBANOS','TX'),
   ('IND','LOS INDIOS','TX'),
   ('LOI','LOS INDIOS','TX'),
   ('MRS','MARFA','TX(BPS)'),
   ('MCA','MCALLEN','TX'),
   ('MAF','ODESSA REGIONAL','TX'),
   ('PDN','PASO DEL NORTE','TX'),
   ('PBB','PEACE BRIDGE','NY'),
   ('PHR','PHARR','TX'),
   ('PAR','PORT ARTHUR','TX'),
   ('ISB','PORT ISABEL','TX'),
   ('POE','PORT OF EL PASO','TX'),
   ('PRE','PRESIDIO','TX'),
   ('PGR','PROGRESO','TX'),
   ('RIO','RIO GRANDE CITY','TX'),
   ('ROM','ROMA','TX'),
   ('SNA','SAN ANTONIO','TX'),
   ('SNN','SANDERSON','TX'),
   ('VIB','VETERAN INTL BRIDGE','TX'),
   ('YSL','YSLETA','TX'),
   ('CHA','CHARLOTTE AMALIE','VI'),
   ('CHR','CHRISTIANSTED','VI'),
   ('CRU','CRUZ BAY, STJOHN','VI'),
   ('FRK','FREDERIKSTED','VI'),
   ('STT','ST THOMAS','VI'),
   ('LGU','CACHE AIRPORT - LOGAN','UT'),
   ('SLC','SALT LAKE CITY','UT'),
   ('CHO','ALBEMARLE CHARLOTTESVILLE','VA'),
   ('DAA','DAVISON AAF - FAIRFAX CNTY','VA'),
   ('HOP','HOPEWELL','VA'),
   ('HEF','MANASSAS','VA#ARPT'),
   ('NWN','NEWPORT','VA'),
   ('NOR','NORFOLK','VA'),
   ('RCM','RICHMOND','VA'),
   ('ABS','ALBURG SPRINGS','VT'),
   ('ABG','ALBURG','VT'),
   ('BEB','BEEBE PLAIN','VT'),
   ('BEE','BEECHER FALLS','VT'),
   ('BRG','BURLINGTON','VT'),
   ('CNA','CANAAN','VT'),
   ('DER','DERBY LINE','VT (I-91)'),
   ('DLV','DERBY LINE','VT (RT.5)'),
   ('ERC','EAST RICHFORD','VT'),
   ('HIG','HIGH GATE SPRINGS','VT'),
   ('MOR','MORSES LINE','VT'),
   ('NPV','NEWPORT','VT'),
   ('NRT','NORTH TROY','VT'),
   ('NRN','NORTON','VT'),
   ('PIV','PINNACLE ROAD','VT'),
   ('RIF','RICHFORT','VT'),
   ('STA','ST ALBANS','VT'),
   ('SWB','SWANTON','VT(BP-SECTORHQ)'),
   ('WBE','WEST BERKSHIRE','VT'),
   ('ABE','ABERDEEN','WA'),
   ('ANA','ANACORTES','WA'),
   ('BEL','BELLINGHAM','WA'),
   ('BLI','BELLINGHAM','WASHINGTON #INTL'),
   ('BLA','BLAINE','WA'),
   ('BWA','BOUNDARY','WA'),
   ('CUR','CURLEW','WA(BPS)'),
   ('DVL','DANVILLE','WA'),
   ('EVE','EVERETT','WA'),
   ('FER','FERRY','WA'),
   ('FRI','FRIDAY HARBOR','WA'),
   ('FWA','FRONTIER','WA'),
   ('KLM','KALAMA','WA'),
   ('LAU','LAURIER','WA'),
   ('LON','LONGVIEW','WA'),
   ('MET','METALINE FALLS','WA'),
   ('MWH','MOSES LAKE GRANT COUNTY ARPT','WA'),
   ('NEA','NEAHBAY','WA'),
   ('NIG','NIGHTHAWK','WA'),
   ('OLY','OLYMPIA','WA'),
   ('ORO','OROVILLE','WA'),
   ('PWB','PASCO','WA'),
   ('PIR','POINT ROBERTS','WA'),
   ('PNG','PORT ANGELES','WA'),
   ('PTO','PORT TOWNSEND','WA'),
   ('SEA','SEATTLE','WA'),
   ('SPO','SPOKANE','WA'),
   ('SUM','SUMAS','WA'),
   ('TAC','TACOMA','WA'),
   ('PSC','TRI-CITIES - PASCO','WA'),
   ('VAN','VANCOUVER','WA'),
   ('AGM','ALGOMA','WI'),
   ('BAY','BAYFIELD','WI'),
   ('GRB','GREEN BAY','WI'),
   ('MNW','MANITOWOC','WI'),
   ('MIL','MILWAUKEE','WI'),
   ('MSN','TRUAX FIELD - DANE COUNTY','WI'),
   ('CHS','CHARLESTON','WV'),
   ('CLK','CLARKSBURG','WV'),
   ('BLF','MERCER COUNTY','WV'),
   ('CSP','CASPER','WY'),
   ('XXX','NOT REPORTED / UNKNOWN',''),
   ('888','UNIDENTIFED AIR / SEAPORT',''),
   ('UNK','UNKNOWN POE',''),
   ('CLG','CALGARY','CANADA'),
   ('EDA','EDMONTON','CANADA'),
   ('YHC','HAKAIPASS','CANADA'),
   ('HAL','Halifax, NS','Canada'),
   ('MON','MONTREAL','CANADA'),
   ('OTT','OTTAWA','CANADA'),
   ('YXE','SASKATOON','CANADA'),
   ('TOR','TORONTO','CANADA'),
   ('VCV','VANCOUVER','CANADA'),
   ('VIC','VICTORIA','CANADA'),
   ('WIN','WINNIPEG','CANADA'),
   ('AMS','AMSTERDAM-SCHIPHOL','NETHERLANDS'),
   ('ARB','ARUBA','NETHANTILLES'),
   ('BAN','BANKOK','THAILAND'),
   ('BEI','BEICA #ARPT','ETHIOPIA'),
   ('PEK','BEIJING CAPITAL INTL','PRC'),
   ('BDA','KINDLEY FIELD','BERMUDA'),
   ('BOG','BOGOTA, EL DORADO #ARPT','COLOMBIA'),
   ('EZE','BUENOS AIRES, MINISTRO PIST','ARGENTINA'),
   ('CUN','CANCUN','MEXICO'),
   ('CRQ','CARAVELAS, BA #ARPT','BRAZIL'),
   ('MVD','CARRASCO','URUGUAY'),
   ('DUB','DUBLIN','IRELAND'),
   ('FOU','FOUGAMOU #ARPT','GABON'),
   ('FBA','FREEPORT','BAHAMAS'),
   ('MTY','GEN M. ESCOBEDO, Monterrey','MX'),
   ('HMO','GEN PESQUEIRA GARCIA','MX'),
   ('GCM','GRANDCAYMAN','CAYMANISLAND'),
   ('GDL','GUADALAJARA, MIGUEL HIDAL','MX'),
   ('HAM','HAMILTON','BERMUDA'),
   ('ICN','INCHON','SEOUL KOREA'),
   ('IWA','INVALID-IWAKUNI','JAPAN'),
   ('CND','KOGALNICEANU','ROMANIA'),
   ('LAH','LABUHA ARPT','INDONESIA'),
   ('DUR','LOUIS BOTHA','SOUTHAFRICA'),
   ('MAL','MANGOLE ARPT','INDONESIA'),
   ('MDE','MEDELLIN','COLOMBIA'),
   ('MEX','JUAREZ INTL, MEXICOCITY','MX'),
   ('LHR','MIDDLESEX','ENGLAND'),
   ('NBO','NAIROBI','KENYA'),
   ('NAS','NASSAU','BAHAMAS'),
   ('NCA','NORTH CAICOS','TURK & CAIMAN'),
   ('PTY','OMAR TORRIJOS','PANAMA'),
   ('SPV','PAPUA','NEW GUINEA'),
   ('UIO','QUITO(MARISCAL SUCR)','ECUADOR'),
   ('RIT','ROME','ITALY'),
   ('SNO','SAKONNAKHON #ARPT','THAILAND'),
   ('SLP','SANLUISPOTOSI #ARPT','MEXICO'),
   ('SAN','SAN SALVADOR','ELSALVADOR'),
   ('SRO','SANTANA RAMOS #ARPT','COLOMBIA'),
   ('GRU','GUARULHOS INTL SAO PAULO','BRAZIL'),
   ('SHA','SHANNON','IRELAND'),
   ('HIL','SHILLAVO','ETHIOPIA'),
   ('TOK','TOROKINA #ARPT','PAPUA NEW GUINEA'),
   ('VER','VERACRUZ','MEXICO'),
   ('LGW','WEST SUSSEX','ENGLAND'),
   ('ZZZ','MEXICO Land (Banco de Mexico)',''),
   ('CHN','No PORT Code (CHN)',''),
   ('CNC','CANNON CORNERS','NY'),
   ('MAA','AbuDhabi',''),
   ('AG0','MAGNOLIA','AR'),
   ('BHM','BAR HARBOR','ME'),
   ('BHX','BIRMINGHAM','AL'),
   ('CAK','AKRON','OH'),
   ('FOK','SUFFOLK COUNTY','NY'),
   ('LND','LANDER','WY'),
   ('MAR','MARFA','TX'),
   ('MLI','MOLINE','IL'),
   ('RIV','RIVERSIDE','CA'),
   ('RME','ROME','NY'),
   ('VNY','VAN NUYS','CA'),
   ('YUM','YUMA','AZ'),
   ('FRG','Collapsed (FOK) 06/15',''),
   ('HRL','Collapsed (HLG) 06/15',''),
   ('ISP','Collapsed (FOK) 06/15',''),
   ('JSJ','Collapsed (SAJ) 06/15',''),
   ('BUS','Collapsed (BUF) 06/15',''),
   ('IAG','Collapsed (NIA) 06/15',''),
   ('PHN','Collapsed (PHU) 06/15',''),
   ('STN','Collapsed (STR) 06/15',''),
   ('VMB','Collapsed (VNB) 06/15',''),
   ('T01','Collapsed (SEA) 06/15',''),
   ('PHF','No PORT Code (PHF)',''),
   ('DRV','No PORT Code (DRV)',''),
   ('FTB','No PORT Code (FTB)',''),
   ('GAC','No PORT Code (GAC)',''),
   ('GMT','No PORT Code (GMT)',''),
   ('JFA','No PORT Code (JFA)',''),
   ('JMZ','No PORT Code (JMZ)',''),
   ('NC8','No PORT Code (NC8)',''),
   ('NYL','No PORT Code (NYL)',''),
   ('OAI','No PORT Code (OAI)',''),
   ('PCW','No PORT Code (PCW)',''),
   ('WA5','No PORT Code (WAS)',''),
   ('WTR','No PORT Code (WTR)',''),
   ('X96','No PORT Code (X96)',''),
   ('XNA','No PORT Code (XNA)',''),
   ('YGF','No PORT Code (YGF)',''),
   ('5T6','No PORT Code (5T6)',''),
   ('060','No PORT Code (60)',''),
   ('SP0','No PORT Code (SP0)',''),
   ('W55','No PORT Code (W55)',''),
   ('X44','No PORT Code (X44)',''),
   ('AUH','No PORT Code (AUH)',''),
   ('RYY','No PORT Code (RYY)',''),
   ('SUS','No PORT Code (SUS)',''),
   ('74S','No PORT Code (74S)',''),
   ('ATW','No PORT Code (ATW)',''),
   ('CPX','No PORT Code (CPX)',''),
   ('MTH','No PORT Code (MTH)',''),
   ('PFN','No PORT Code (PFN)',''),
   ('SCH','No PORT Code (SCH)',''),
   ('ASI','No PORT Code (ASI)',''),
   ('BKF','No PORT Code (BKF)',''),
   ('DAY','No PORT Code (DAY)',''),
   ('Y62','No PORT Code (Y62)',''),
   ('AG','No PORT Code (AG)',''),
   ('BCM','No PORT Code (BCM)',''),
   ('DEC','No PORT Code (DEC)',''),
   ('PLB','No PORT Code (PLB)',''),
   ('CXO','No PORT Code (CXO)',''),
   ('JBQ','No PORT Code (JBQ)',''),
   ('JIG','No PORT Code (JIG)',''),
   ('OGS','No PORT Code (OGS)',''),
   ('TIW','No PORT Code (TIW)',''),
   ('OTS','No PORT Code (OTS)',''),
   ('AMT','No PORT Code (AMT)',''),
   ('EGE','No PORT Code (EGE)',''),
   ('GPI','No PORT Code (GPI)',''),
   ('NGL','No PORT Code (NGL)',''),
   ('OLM','No PORT Code (OLM)',''),
   ('.GA','No PORT Code (.GA)',''),
   ('CLX','No PORT Code (CLX)',''),
   ('CP','No PORT Code (CP)',''),
   ('FSC','No PORT Code (FSC)',''),
   ('NK','No PORT Code (NK)',''),
   ('ADU','No PORT Code (ADU)',''),
   ('AKT','No PORT Code (AKT)',''),
   ('LIT','No PORT Code (LIT)',''),
   ('A2A','No PORT Code (A2A)',''),
   ('OSN','No PORT Code (OSN)','')
]